export const CONFIG = {
  CELL_SIZE: 4,
  MAX_SHOTS: 10,
  PROJECTILE_SPEED_SCALE: 0.10,
};

export const GAME_STATE = {
  P1_TURN: "P1_TURN",
  P2_TURN: "P2_TURN",
  PROJECTILE_AIRBORNE: "PROJECTILE_AIRBORNE",
  GAME_OVER: "GAME_OVER",
};